### PR TITLE
Feature add attachment to card

### PR DESCRIPTION
**Pull request by gusehr**
@julienvey added binary attachment to cards (Only Apache Http implementation)
A new module of Apache Http Components is required when use Apache Http Client.
See updated documentation.

### CODE REVIEW

**Comment by gusehr** [comment]
Hi @julienvey.
Have you analyzed this pull request?

I have another API method implemented on my repository.
I'd like to send it to you after this merge.

Thanks in advance.

**Comment by julienvey** [comment]
Hi @gusehr 

Looks Good to merge ! 

Can you rebase & squash your commits into a single commit ? I will merge after that

**Comment by gusehr** [comment]
OK @julienvey! 
I'll dig for how to do it.
I'm not a git expert, but that is a learning opportunity \o/

**Comment by gusehr** [comment]
@julienvey I couldn't squash the "merge" commits.
But I think the pull request is better now.
Can you check it?

Thank you.

**Comment by alexeyOnGitHub** [comment]
oops, this was automatically closed when I deleted old "dev" branch. 
I checked out this branch locally, fixed merge conflicts. submitted https://github.com/taskadapter/trello-java-wrapper/pull/32
note - I have NOT verified that the code works (yet) and this changeset does not have any test.
@gusehr  you are welcome to submit some basic test for this feature.

**Pull request closed without merging**
