### PR TITLE
Implement Trello API credentials provider from various sources.

### PR DESCRIPTION
**Pull request by nstdio**

### CODE REVIEW

**Comment by nstdio** [comment]
@alexeyOnGitHub any comments ?

**Comment by alexeyOnGitHub** [comment]
hey, I am yet not convinced this should be a part of the library. 
this is just util code to load command-line params or files or env variables or whatnot. 

the API entry point is an instance of TrelloImpl with credentials, and it is up to the application where to load those credentials from. with minor changes, the code in thi sPR may as well be in a generic "app configuration" library not related to Trello at all.

I understand that having util code like this would simplify usage, but at the same time this places certain limits on how credentials will be loaded (e.g. specific command line parameter names and such). the library itself should not impose restrictions like that, its configuration layer should be orthogonal to the library runtime operations.
let me think about this later

**Comment by nstdio** [comment]
As far as I know and my experience tells me solid API client witch does use secret credentials provides out-of-box support for this kind of stuff. For example Amazon CLI reads credentials from a file or command line arguments. This is common pattern. In production no one would hard-code the secret credentials. So I think that the `credentials` package is out-of-box solution for the users. If user still wants  to hard code credentials he can simple use `SimpleCredentialsProvider`.

Basically without `credentials` package we forcing users to do common job that he would do anyway.

> this is just util code to load command-line params or files or env variables or whatnot.

Yes, this is util code that user would do anyway, we simplify their jobs at the same time we stay flexible.

> the API entry point is an instance of TrelloImpl with credentials, and it is up to the application where to load those credentials from.
It still up to application from where load its credentials, nothing changed.

> with minor changes, the code in thi sPR may as well be in a generic "app configuration" library not related to Trello at all.

That's where flexibility shows up.

> I understand that having util code like this would simplify usage, but at the same time this places certain limits on how credentials will be loaded

I would not say so, users still can supply credentials whether they want.

> the library itself should not impose restrictions like that, its configuration layer should be orthogonal to the library runtime operations.

Can you explain in more details, I don't get what you mean.

**Comment by nstdio** [comment]
@alexeyOnGitHub any progress ?

**Comment by nstdio** [comment]
@alexeyOnGitHub any progress ?

**Comment by alexeyOnGitHub** [comment]
I am going on vacation and I won't be able to review this for a while. I do not see this as an urgent requirement since this is generic parameters parsing and handling code

**Comment by nstdio** [comment]
Yes, this is not an urgent feature, but this is a backward compatible change and users who implemented their own credentials loading would not notice any change. Beside that as I said in a comments above, this is a common practice for API clients to provide out of box credentials loaders, at the same time giving users freedom to choose whether use them or not.

I really don't see any obstacle to merge this. I addressed all your comments and still don't understand the practical, design, usage failures in this PR.

**Comment by nstdio** [comment]
Is this gonna be merged?

**Comment by alexeyOnGitHub** [comment]
hi! thank you for your PR. I looked at it again and decided that I was not comfortable with adding this into the library. I understand that this is reusable code, but at the same time I do not see a strong enough case to justify having 800+ extra lines of code in the project - something we would need to maintain in the future. I want the library to focus on Trello interactions and not go beyond that.

I understand that some other libraries decided to include configuration layers, but so far there was no demand for this in this library.

**Pull request closed without merging**
